name: laxis
description: "Laxis - Language Learning Game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # Local packages
  laxis_ui:
    path: packages/laxis_ui
  laxis_engine:
    path: packages/laxis_engine
  german_language_module:
    path: packages/german_language_module
  language_module_interface:
    path: packages/language_module_interface
  core:
    path: packages/core
  
  # External dependencies
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
