name: german_language_module
description: Implementation for German (Flutter package, for assets).

dependencies:
  flutter:
    sdk: flutter
  language_module_interface:
    path: ../language_module_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/german_a1.json
    - assets/german_a2.json
