name: core
description: Shared utilities, data models, services.

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

dev_dependencies:
  lints: ^5.1.1
