name: laxis_ui
description: All reusable UI widgets (Flutter package).

dependencies:
  flutter:
    sdk: flutter
  laxis_engine:
    path: ../laxis_engine
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
