name: laxis_ui
description: All reusable UI widgets (Flutter package).

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  laxis_engine:
    path: ../laxis_engine
  core:
    path: ../core
  language_module_interface:
    path: ../language_module_interface
  german_language_module:
    path: ../german_language_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
